(require-library readline)
;(print (gnu-history-goto 1))
;(print (gnu-search-history-backward "a"))
;(print (gnu-search-history-backward "b"))
;(print (gnu-search-history-backward "c"))
(print (gnu-history-list))
