language: c
compiler:
  - clang
  - gcc-4.4
  - gcc-4.5
  - gcc-4.6
  - gcc
install:
  - sudo apt-get install clang
  - sudo apt-get install libchicken-dev chicken-bin
  - sudo apt-get install gcc-4.
script:
  - make
