language: c
compiler:
  - clang
  - gcc-4.4
  - gcc-4.6
  - gcc-4.7
  - gcc-4.8
  - gcc
  - tcc
install:
  - sudo apt-get install clang
  - sudo apt-get install gcc-4.4 gcc-4.7 gcc-4.8 gcc-4.6 tcc
  - sudo apt-get install libchicken-dev chicken-bin
  - sudo chicken-install -s readline
script:
  - make
after_success:
  - cd readline/trunk && make check
