;;;; versions.import.scm - GENERATED BY CHICKEN 4.10.0 -*- Scheme -*-

(eval '(import
         chicken
         scheme
         srfi-1
         srfi-13
         data-structures
         irregex
         posix
         utils
         (only extras fprintf)
         http-client
         uri-generic))
(##sys#register-compiled-module
  'versions
  (list)
  '((make-version . versions#make-version)
    (version? . versions#version?)
    (version:label . versions#version:label)
    (version:major . versions#version:major)
    (version:major-set! . versions#version:major-set!)
    (version:minor . versions#version:minor)
    (version:micro . versions#version:micro)
    (version:patch . versions#version:patch)
    (version:extra . versions#version:extra)
    (string->version . versions#string->version)
    (version->string . versions#version->string)
    (version-compare . versions#version-compare)
    (version=? . versions#version=?)
    (version<? . versions#version<?)
    (version<=? . versions#version<=?)
    (version>? . versions#version>?)
    (version>=? . versions#version>=?)
    (version-newer? . versions#version-newer?)
    (version-older? . versions#version-older?)
    (version-exact? . versions#version-exact?)
    (version-sort . versions#version-sort)
    (update-version . versions#update-version)
    (bump:major . versions#bump:major)
    (bump:minor . versions#bump:minor)
    (bump:micro . versions#bump:micro)
    (bump:patch . versions#bump:patch)
    (bump . versions#bump)
    (bump:major! . versions#bump:major!)
    (bump:minor! . versions#bump:minor!)
    (bump:micro! . versions#bump:micro!)
    (bump:patch! . versions#bump:patch!)
    (bump! . versions#bump!)
    (local . versions#local)
    (remote . versions#remote)
    (update-available? . versions#update-available?))
  (list)
  (list))

;; END OF FILE
