;;;; readline.import.scm - GENERATED BY CHICKEN 4.9.0.1 -*- Scheme -*-

(eval '(import scheme chicken foreign ports data-structures posix))
(##sys#register-compiled-module
  'readline
  (list)
  '((gnu-readline . readline#gnu-readline)
    (make-gnu-readline-port . readline#make-gnu-readline-port)
    (%gnu-readline-signal-cleanup . readline#%gnu-readline-signal-cleanup)
    (gnu-readline-clear-history . readline#gnu-readline-clear-history)
    (gnu-readline-read-history . readline#gnu-readline-read-history)
    (gnu-readline-write-history . readline#gnu-readline-write-history)
    (gnu-readline-append-history . readline#gnu-readline-append-history)
    (gnu-readline-truncate-history . readline#gnu-readline-truncate-history)
    (gnu-history-new-lines . readline#gnu-history-new-lines)
    (gnu-history-install-file-manager
      .
      readline#gnu-history-install-file-manager)
    (gnu-readline-parse-and-bind . readline#gnu-readline-parse-and-bind)
    (gnu-readline-set-bounce-ms . readline#gnu-readline-set-bounce-ms)
    (gnu-readline-completions . readline#gnu-readline-completions))
  (list)
  (list))

;; END OF FILE
